title: "Puspita Chowdhury"
name: "Puspita Chowdhury"
url: "https://puspitachowdhury.github.io"

author:
  name: "Puspita Chowdhury"
  avatar: "/images/profile.jpg"
  bio: "MS in AI @ YU • AI ethics & data projects • Open to internships"
  location: "New York, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yourname@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/puspitachowdhury"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/your-handle/"
