title: "Puspita Chowdhury"
logo: /assets/img/headshot_circle.png
description: "MS in Artificial Intelligence & Data • AI Solutions for Social Impact"
show_downloads: false
theme: jekyll-theme-hacker

# Optional extras
github:
  is_project_page: true
  repository_url: https://github.com/puspitachy/Puspita.github.io
  owner_url: https://github.com/puspitachy

