title: "Puspita Chowdhury"
name: "Puspita Chowdhury"
description: "AI • Data • Ethics — Portfolio"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
# If you want a custom domain, set it here:
# domain: "yourdomain.com"
# url: "https://yourdomain.com"
url: "https://USERNAME.github.io"
baseurl: ""

# Author profile (sidebar)
author:
  name: "Puspita Chowdhury"
  avatar: "/images/profile.jpg"
  bio: "MS in AI @ YU • AI ethics & data projects • Open to internships"
  location: "New York, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:you@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/USERNAME"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR-LINK/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"
    - label: "Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/resume.pdf"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-include-cache

# Navigation (from _data/navigation.yml)
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # projects collection
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

# Include custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Enable analytics later if needed
# google_analytics: G-XXXXXXXXXX
